[platformio]
default_envs = mamba_usb
core_dir = .tools/platformio

[env:mamba_usb]
platform = platformio/ststm32@20.0.0
board = genericSTM32F405RG
framework = arduino
platform_packages =
    platformio/framework-arduinoststm32@4.30000.0
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D HSE_VALUE=8000000U
monitor_speed = 115200
upload_protocol = dfu
build_src_filter = +<*> -<imu_spi.cpp>

[env:mamba_spi]
extends = env:mamba_usb
build_src_filter = +<*> -<main.cpp>
lib_deps =
    https://github.com/finani/ICM42688.git#b417e0ab80650201dcb321a3d306a8d51464a20a
